# Copyright 2021 IRT Saint Exupéry, https://www.irt-saintexupery.com
#
# This work is licensed under a BSD 0-Clause License.
#
# Permission to use, copy, modify, and/or distribute this software
# for any purpose with or without fee is hereby granted.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL
# WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL
# THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT,
# OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING
# FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT,
# NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION
# WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
"""# Find a global optimum with a local algorithm

## Problem

Local optimization algorithms converge to the nearest local optimum
and may miss the global one on multimodal problems.
You want to use a local algorithm to find the global optimum of such a problem.

## Solution

Use the `MultiStart` algorithm, which generates several starting points
via a DOE algorithm and runs a local optimization from each one.
The best local optimum across all starting points is returned as the result.

## Step-by-step guide
"""

from __future__ import annotations

from gemseo import execute_post
from gemseo.discipline import AnalyticDiscipline
from gemseo.doe import PYDOE_FULLFACT_Settings
from gemseo.optimization import SLSQP_Settings
from gemseo.optimization.multi_start.settings.multi_start_settings import (
    MultiStart_Settings,
)
from gemseo.post import BasicHistory_Settings
from gemseo.scenario import MDOScenario
from gemseo.space import DesignSpace

# %%
# ### 1. Build the multimodal problem
#
# You define a constrained problem with a multimodal objective $x^3 - x + 1$:
objective = AnalyticDiscipline({"obj": "x**3-x+1"})
constraint = AnalyticDiscipline({"cstr": "x**2+obj**2-1.5"})

design_space = DesignSpace()
design_space.add_variable("x", lower_bound=-1.5, upper_bound=1.5, value=1.5)

scenario = MDOScenario([objective, constraint], design_space)
scenario.add_objective("obj")
scenario.add_constraint("cstr", constraint_type="ineq")

# %%
# ### 2. Execute with the MultiStart algorithm
#
# Combine a local algorithm (SLSQP) with a DOE to generate starting points
# (here, a 10-point full-factorial design).
# Set `multistart_file_path` to save the history of local optima:
scenario.execute(
    MultiStart_Settings(
        max_iter=100,
        opt_algo_settings=SLSQP_Settings(),
        doe_algo_settings=PYDOE_FULLFACT_Settings(n_samples=10),
        multistart_file_path="multistart.hdf5",
    )
)

# %%
# ### 3. Inspect the results
#
# Plot the full history (all sub-optimization iterations concatenated):
execute_post(
    scenario, BasicHistory_Settings(variable_names=["obj"], save=False, show=True)
)

# %%
# Or plot only the local optima (one per starting point)
# from the multistart history file:
execute_post(
    "multistart.hdf5",
    BasicHistory_Settings(variable_names=["obj"], save=False, show=True),
)

# %%
# ## Summary
#
# The `MultiStart` algorithm wraps any local optimization algorithm
# and runs it from multiple starting points generated by a DOE.
# Use `multistart_file_path` to save the local optima history
# and inspect it separately from the full optimization history.
