# Read the Docs configuration file.
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details.

version: 2

sphinx:
  configuration: doc_src/conf.py

python:
  install:
    - requirements: requirements/doc.txt
    - path: .
      extra_requirements:
        - all

build:
  os: ubuntu-20.04
  tools:
    python: "3.12"
  apt_packages:
    - graphviz
    - plantuml
  jobs:
    post_checkout:
      # Tags are necessary for setuptools-scm to determine the version.
      - git fetch --tags
      - git fetch origin develop
    post_install:
      - pip install --no-deps -r requirements/doc-plugins.txt
    pre_build:
      - sphinx-apidoc -e -M -o doc_src/modules src/gemseo
