[global]
flavor = "mkdocs"
disable = ["MD013", "MD024", "MD033", "MD041", "MD052", "MD059"]

[code-block-tools]
enabled = true

[code-block-tools.languages.python]
lint = ["ruff:check"]
format = ["ruff:format"]
on-error = "ignore"
