name: gemseo
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip
  # The following dependencies must be the same as in requirements/gemseo-conda-python3.txt
  - python-graphviz <=0.15
  - nlopt >=2.4.2,<=2.6.2
