[tox]
min_version = 4
requires = tox-uv

[testenv]
# Uses uv.lock for reproducible deps (equivalent: uv sync --locked --extra all --group dev)
runner = uv-venv-lock-runner
extras = all
dependency_groups = dev
set_env =
    # Workaround matplotlib on windows server 2012 and gitlab-runner,
    # matplotlib cannot access a registry key and falls back to the WINDIR var
    # https://matplotlib.org/stable/api/font_manager_api.html#matplotlib.font_manager.win32FontDirectory.
    WINDIR = {env:WINDIR:C:\Windows}
    # Define pytest options for using coverage.
    coverage: __COVERAGE_POSARGS = --cov --cov-report=xml --cov-report=html --no-cov-on-fail
commands =
    pytest {env:__COVERAGE_POSARGS:} {posargs}

[testenv:min-deps-versions]
# TODO: verify this env that does not install the lowest versions of numpy at least, as compared to using pip-compile.
description = test with the minimum versions of the dependencies
# The lock file does not contain the lowest-direct dependencies,
# thus we use the runner that does not use the lock file.
runner = uv-venv-runner
uv_resolution = lowest-direct
basepython = python3.10

[testenv:check-types]
description = run type checking
basepython = python3.14
dependency_groups = check-types
commands =
    mypy {posargs}

[testenv:doc]
description = build documentation
basepython = python3.14
dependency_groups = doc
set_env =
    DOCSTRING_INHERITANCE_ENABLE = 1
commands =
    mkdocs serve {posargs}

[testenv:doc-fast]
description = build documentation without api
base = doc
commands =
    mkdocs serve --config-file mkdocs-fast.yml {posargs}

[testenv:pypi-py{310,311,312,313}]
description = test the pypi distribution
runner = uv-venv-runner
skip_install = true
deps =
    gemseo[all]
    pytest-xdist

# Below are environments that do not install gemseo at all.

[no-install]
basepython = python3.14
# Base internal configuration from scratch,
# nothing is inherited from [testenv].
skip_install = true

[testenv:check]
description = run code formatting and checking
base = no-install
deps = -r requirements/check.txt
allowlist_externals = prek
commands =
    prek install
    prek run --all-files

[testenv:dist]
description = create and check the pypi distribution
base = no-install
deps =
    check-wheel-contents
    uv
allowlist_externals = rm
commands =
    rm -rf dist build
    uv build
    # W002: ignore duplicated files.
    check-wheel-contents dist --ignore W002

[testenv:dist-upload]
description = upload existing distribution files to a package repository
base = no-install
deps = uv
commands =
    uv publish

[testenv:update-deps]
description = update the envs dependencies
base = no-install
deps =
    prek
    uv
allowlist_externals = prek
commands =
    prek autoupdate
    uv pip compile --upgrade requirements/check.in -o requirements/check.txt
    uv lock --upgrade
