..
   Copyright 2021 IRT Saint Exupéry, https://www.irt-saintexupery.com

   This work is licensed under the Creative Commons Attribution-ShareAlike 4.0
   International License. To view a copy of this license, visit
   http://creativecommons.org/licenses/by-sa/4.0/ or send a letter to Creative
   Commons, PO Box 1866, Mountain View, CA 94042, USA.

..
   Contributors:
          :author: Matthias De Lozzo

Learn the basics of **|g|** through a series of tutorials:

	- Tutorial 1: Solve an optimization problem - :ref:`See more...  <simple_opt_example>`
	- Tutorial 2: Solve a :term:`MDO` problem - :ref:`See more...  <sellar_mdo>`
	- Tutorial 3: Carry out a trade-off study - :ref:`See more...  <sobieski_doe>`
	- Tutorial 4: Build a :ref:`scalable model <scalable>` (Sellar) - :ref:`See more...   <sellar_scalable>`
	- Tutorial 5: Build a :ref:`scalable model <scalable>` (Aerostructure) - :ref:`See more...   <aerostruct_toy_example>`
	- Application: Sobieski's SSBJ - :ref:`See more...  <sobieski_mdo>`
	- Problems: Train with benchmark problems - :ref:`See more...  <benchmark_problems>`
