..
   Copyright 2021 IRT Saint Exupéry, https://www.irt-saintexupery.com

   This work is licensed under the Creative Commons Attribution-ShareAlike 4.0
   International License. To view a copy of this license, visit
   http://creativecommons.org/licenses/by-sa/4.0/ or send a letter to Creative
   Commons, PO Box 1866, Mountain View, CA 94042, USA.

..
   Contributors:
          :author: Matthias De Lozzo

Discover:

	- what is in the **|g|** package - :ref:`See more... <package_description>`,
	- what are the :ref:`mandatory <mandatory_dependencies>` and :ref:`additional <additional_dependencies>` dependencies - :ref:`See more... <dependencies>`,
	- how to install the Python library **|g|** - :ref:`See more... <how_to_install>`,
	- how to run the unitary tests - :ref:`See more... <test_gemseo>`,
	- how to run some examples - :ref:`See more... <test_by_experimenting>`.
