..
   Copyright 2021 IRT Saint Exupéry, https://www.irt-saintexupery.com

   This work is licensed under the Creative Commons Attribution-ShareAlike 4.0
   International License. To view a copy of this license, visit
   http://creativecommons.org/licenses/by-sa/4.0/ or send a letter to Creative
   Commons, PO Box 1866, Mountain View, CA 94042, USA.

..
   Contributors:
          :author: Matthias De Lozzo

**|g|** stands for Generic Engine for `Multidisciplinary Design Optimization <https://en.wikipedia.org/wiki/Multidisciplinary_design_optimization>`_ Scenarios.

Built on top of `NumPy  <http://www.numpy.org/>`_, `SciPy  <http://www.scipy.org/>`_ and `matplotlib  <http://www.matplotlib.org/>`_ libraries,
this `Python <https://www.python.org/>`__ library enables an automatic resolution of design problems (optimization, sampling, visualization, ...).

**|g|** is more particularly specialized in `Multidisciplinary Design Optimization <https://en.wikipedia.org/wiki/Multidisciplinary_design_optimization>`_ (:term:`MDO`).
