..
   Copyright 2021 IRT Saint Exupéry, https://www.irt-saintexupery.com

   This work is licensed under the Creative Commons Attribution-ShareAlike 4.0
   International License. To view a copy of this license, visit
   http://creativecommons.org/licenses/by-sa/4.0/ or send a letter to Creative
   Commons, PO Box 1866, Mountain View, CA 94042, USA.

..
   Contributors:
          :author: Matthias De Lozzo

Fully based on the power of object-oriented programming, the :term:`scenario` automatically generates the :term:`process`, with corresponding :term:`work flow` and :term:`data flow`.

**|g|** aims at pushing forward the limits of automation in simulation processes development, with a particular focus made on:

	- the integration of heterogeneous simulation environments in industrial and research contexts
	- the integration of state of the art algorithms for optimization, design of experiments, and coupled analyses
	- the automation of :term:`MDO` results analysis
	- the development of distributed and multi-level :ref:`MDO formulations <mdo_formulations>`

.. figure:: /_images/bilevel_ssbj.png

   A bi-level MDO formulation on Sobieski's SSBJ test case.
