# Copyright 2021 IRT Saint Exupéry, https://www.irt-saintexupery.com
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License version 3 as published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program; if not, write to the Free Software Foundation,
# Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
"""Settings for post-processing."""

from __future__ import annotations

from pydantic import BaseModel
from pydantic import Field
from pydantic import PositiveFloat

from gemseo.util.pydantic import BaseSettings
from gemseo.util.typing import StrPath

_USE_STANDARDIZED_OBJECTIVE_DESCRIPTION = (
    "Whether to use the standardized objective for post-processing. "
    "The standardized objective corresponds to the original one expressed as a "
    "cost function to minimize. "
    "A "
    "[BaseDriverLibrary][gemseo.core.algorithm.base_driver_library.BaseDriverLibrary] "
    "works with this standardized objective and the "
    "[Database][gemseo.core.problem.database.Database] "
    "stores its values. "
    "However, for convenience, "
    "it may be more relevant to log the expression "
    "and the values of the original objective."
)


class UseStandardizedObjectiveMixin(BaseModel):
    """Mixin adding ``use_standardized_objective`` to post-processor settings."""

    use_standardized_objective: bool = Field(
        default=True,
        description=_USE_STANDARDIZED_OBJECTIVE_DESCRIPTION,
    )


class BasePostSettings(BaseSettings):
    """The settings common to all the post-processing classes."""

    save: bool = Field(
        default=True,
        description="Whether to save the figure.",
    )
    show: bool = Field(
        default=False,
        description="Whether to display the figure.",
    )
    use_best_iteration_history: bool = Field(
        default=False,
        description="Whether to use the best iteration history "
        "rather than the iteration history.",
    )
    file_path: StrPath = Field(
        default="",
        description="The path of the file to save the figures. If the extension is "
        "missing, use `file_extension`. "
        "If empty, create a file path from `directory_path`, `file_name` and "
        "`file_extension`.",
    )
    directory_path: StrPath = Field(
        default="",
        description="The path of the directory to save the figures. "
        "If empty, use the current working directory.",
    )
    file_name: str = Field(
        default="",
        description="The name of the file to save the figures. "
        "If empty, use a default one generated by the post-processing.",
    )
    file_extension: str = Field(
        default="",
        description="A file extension, e.g. 'png', 'pdf', 'svg', ... "
        "If empty, use a default file extension.",
    )
    fig_size: tuple[PositiveFloat, PositiveFloat] = Field(
        default=(11.0, 11.0),
        description="The width and height of the figure in inches, e.g. `(w, h)`.",
    )
