# Copyright 2021 IRT Saint Exupéry, https://www.irt-saintexupery.com
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License version 3 as published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program; if not, write to the Free Software Foundation,
# Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
# Contributors:
#    INITIAL AUTHORS - initial API and implementation and/or initial
#                           documentation
#        :author: Matthias De Lozzo
#    OTHER AUTHORS   - MACROSCOPIC CHANGES
"""Base class for univariate distributions."""

from __future__ import annotations

from abc import abstractmethod
from collections.abc import Mapping
from pathlib import Path
from typing import TYPE_CHECKING
from typing import Any
from typing import ClassVar

import plotly.graph_objects as go
from matplotlib import pyplot as plt
from numpy import arange
from plotly.subplots import make_subplots

from gemseo.uncertainty.distributions.base import BaseDistribution
from gemseo.uncertainty.distributions.base import _DistributionT
from gemseo.uncertainty.distributions.base import _ParametersT
from gemseo.uncertainty.distributions.base import _VariableT
from gemseo.utils.matplotlib_figure import save_show_figure
from gemseo.utils.string_tools import pretty_str

if TYPE_CHECKING:
    from types import ModuleType

    from matplotlib.figure import Figure

    from gemseo.uncertainty.distributions.base_joint import BaseJointDistribution
    from gemseo.uncertainty.distributions.base_settings import (
        BaseGenericDistributionSettings,
    )


class BaseUnivariateDistribution(
    BaseDistribution[_VariableT, _ParametersT, _DistributionT]
):
    """The base class for univariate distributions."""

    JOINT_DISTRIBUTION_CLASS: ClassVar[type[BaseJointDistribution]]
    """The class of the joint distribution associated with this marginal."""

    def plot(  # noqa: D102
        self,
        show: bool = True,
        save: bool = False,
        file_path: str | Path = "",
        directory_path: str | Path = "",
        file_name: str = "",
        file_extension: str = "",
        variable_name: str = "",
    ) -> Figure:
        """Plot the distribution.

        Args:
            save: Whether to save the figure.
            show: Whether to display the figure.
            file_path: The path of the file to save the figure.
                If the extension is missing, use `file_extension`.
                If empty,
                create a file path
                from `directory_path`, `file_name` and `file_extension`.
            directory_path: The path of the directory to save the figures.
                If empty, use the current working directory.
            file_name: The name of the file to save the figures.
                If empty, use a default one generated by the post-processing.
            file_extension: A file extension, e.g. `'png'`, `'pdf'`, `'svg'`, ...
                If empty, use a default file extension.
            variable_name: The name of the variable
                defined by the probability distribution.

        Returns:
            The figure.
        """
        l_b = self.num_lower_bound
        u_b = self.num_upper_bound
        x_values = arange(l_b, u_b, (u_b - l_b) / 100)
        pdf = [self._pdf(x_value) for x_value in x_values]
        cdf = [self._cdf(x_value) for x_value in x_values]
        if file_name == "":
            file_name = f"pdf_cdf_{variable_name}" if variable_name else "pdf_cdf"
        if file_extension == "html":
            fig = make_subplots(cols=2)
            fig.add_trace(go.Scatter(name="PDF", x=x_values, y=pdf), row=1, col=1)
            fig.add_trace(go.Scatter(name="CDF", x=x_values, y=cdf), row=1, col=2)
            fig.layout.xaxis.title.text = variable_name or self.DEFAULT_VARIABLE_NAME
            fig.layout.xaxis2.title.text = variable_name or self.DEFAULT_VARIABLE_NAME
            fig.layout.yaxis.title.text = "Probability density function"
            fig.layout.yaxis2.title.text = "Cumulative distribution function"
            fig.update_layout(title=repr(self))
            if save:
                directory_path = (
                    Path().cwd() if directory_path == "" else Path(directory_path)
                )
                fig.write_html(directory_path / f"{file_name}.{file_extension}")
            if show:
                fig.show()
        else:
            fig, (ax1, ax2) = plt.subplots(ncols=2, figsize=(6.4, 3.2))
            fig.suptitle(repr(self))
            ax1.plot(x_values, pdf)
            ax1.grid()
            ax1.set_xlabel(variable_name or self.DEFAULT_VARIABLE_NAME)
            ax1.set_ylabel("Probability density function")
            ax1.set_box_aspect(1)
            ax2.plot(x_values, cdf)
            ax2.grid()
            ax2.set_xlabel(variable_name or self.DEFAULT_VARIABLE_NAME)
            ax2.set_ylabel("Cumulative distribution function")
            ax2.yaxis.tick_right()
            ax2.set_box_aspect(1)
            if save:
                directory_path = (
                    Path().cwd() if directory_path == "" else Path(directory_path)
                )
                file_path = self._file_path_manager.create_file_path(
                    file_path=file_path,
                    file_name=file_name,
                    directory_path=directory_path,
                    file_extension=file_extension,
                )
            else:
                file_path = ""

            save_show_figure(fig, show, file_path)

        return fig

    @abstractmethod
    def _pdf(
        self,
        value: float,
    ) -> float:
        """Probability density function (PDF).

        Args:
            value: An evaluation point.

        Returns:
            The PDF value at the evaluation point.
        """

    @abstractmethod
    def _cdf(
        self,
        level: float,
    ) -> float:
        """Cumulative distribution function (CDF).

        Args:
            level: A probability level.

        Returns:
            The CDF value for the probability level.
        """

    def _create_distribution_from_module(
        self, module: ModuleType, settings: BaseGenericDistributionSettings
    ) -> Any:
        """Create a distribution from a module.

        Args:
            module: The module.
            settings: The settings of the distribution.

        Returns:
            The distribution.

        Raises:
            ValueError: When the distribution cannot be created from the module.
        """
        distribution_name = settings.interfaced_distribution
        parameters = settings.parameters
        try:
            create_distribution = getattr(module, distribution_name)
        except BaseException:  # noqa: BLE001
            msg = f"{distribution_name} cannot be imported from {module.__name__}."
            raise ImportError(msg) from None

        try:
            if isinstance(parameters, Mapping):
                return create_distribution(**parameters)

            return create_distribution(*parameters)
        except BaseException:  # noqa: BLE001
            msg = f"The arguments of {self} are wrong; more details on {self._WEBSITE}."
            raise ValueError(msg) from None

    def __repr__(self) -> str:
        parameters = self._settings.standard_parameters or self._settings.parameters
        return (
            f"{self._settings.interfaced_distribution}"
            f"({pretty_str(parameters, sort=False)})"
        )

    @property
    def transformation(self) -> str:
        """The transformation applied to the random variable noted `"x"`.

        E.g. `"sin(x)"`.
        """
        return self._transformation
