# Copyright 2021 IRT Saint Exupéry, https://www.irt-saintexupery.com
#
# This work is licensed under a BSD 0-Clause License.
#
# Permission to use, copy, modify, and/or distribute this software
# for any purpose with or without fee is hereby granted.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL
# WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL
# THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT,
# OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING
# FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT,
# NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION
# WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
"""# Full optimization history overview

## Problem

After an optimization, you want a comprehensive view of the history:
design variables, objective, constraint feasibility, and convergence,
all in a single post-processing.

## Solution

Use [OptHistoryView][gemseo.post.opt_history_view.OptHistoryView],
which produces a series of plots:

- **Design variables history**: normalized values of selected design variable
  components across iterations, represented as a color map.
- **Objective function history**: evolution of the objective value across iterations.
- **Distance to best design**: Euclidean distance $||x - x^*||_2$ between each
  iterate and the best design, in log scale.
- **Inequality constraint history**: evolution of constraint values, color-coded
  as red (violated), white (active), or green (satisfied).

## Reading the marks

The *best design* is
the design satisfying the constraints with the best objective value,
or the least infeasible design when no design satisfies the constraints.

Every figure marks the iteration of the best design
with a star on the x-axis and a dashed vertical line.
A problem without an optimum solution has no best design:
its figures carry no such mark
and the plot of the distance to the best design is not drawn.
The figures of the objective and of the constraints also mark the iterations
whose values are `NaN` with a cross on the x-axis
and a dashed vertical line.
The label of the x-axis mentions the marks that the figure draws,
so a figure of a problem with a best design and without `NaN` values
mentions only the star.

Beware that
the objective curve joins the two sides of a `NaN` iteration with a straight segment,
and that the constraint plots draw a `NaN` value with the color of an active constraint:
the crosses are the only way to tell these iterations apart.

## Step-by-step guide
"""

from __future__ import annotations

from gemseo import execute_post
from gemseo.post import OptHistoryView_Settings

# %%
# ### 1. Prerequisites
#
# This how-to requires an HDF5 file generated by a previously executed scenario.
# See [How to post-process an HDF5 file][post-process-an-hdf5-file]
# for more information on how to generate and load such a file.
#
# !!! note
#     The `execute_post` function also handles previously executed instances of `MDOScenario`
#     or `OptimizationProblem`.

# %%
# ### 2. Run the optimization history view
#
# Use `variable_names` to restrict the design variable history plot
# to a subset of variables:
execute_post(
    "sobieski_mdf_scenario.h5",
    settings_model=OptHistoryView_Settings(
        variable_names=["x_1", "x_2"],
        save=False,
        show=True,
    ),
)

# %%
# ## Summary
#
# [OptHistoryView][gemseo.post.opt_history_view.OptHistoryView] provides a
# comprehensive overview of the optimization history in a single post-processing:
# design variable evolution, objective history, convergence distance,
# and constraint feasibility.
# Pass any HDF5 file from a previously executed scenario to
# [execute_post()][gemseo.execute_post].
