# Copyright 2021 IRT Saint Exupéry, https://www.irt-saintexupery.com
#
# This work is licensed under a BSD 0-Clause License.
#
# Permission to use, copy, modify, and/or distribute this software
# for any purpose with or without fee is hereby granted.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL
# WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL
# THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT,
# OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING
# FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT,
# NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION
# WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
"""# Constraint values on a radar chart

## Problem

After an optimisation, you want to visualise the values of multiple constraints
at a given iteration in a compact, readable chart,
especially when the number of constraints is large.

## Solution

Use [ConstraintRadar][gemseo.post.constraint_radar.ConstraintRadar],
which plots selected constraint functions on a radar chart at a given iteration
(default: the last one).
It scales better with the number of constraints than a standard constraint history plot.

## Step-by-step guide
"""

from __future__ import annotations

from gemseo import execute_post
from gemseo.post.constraint_radar_settings import ConstraintRadar_Settings

# %%
# ### 1. Prerequisites
#
# This how-to requires an HDF5 file generated by a previously executed scenario.
# See [How to post-process an HDF5 file][post-process-an-hdf5-file]
# for more information on how to generate and load such a file.
# !!!note
#     The `execute_post` function also handles previously executed instances of `MDOScenario`
#     or `OptimzationProblem`.

# %%
# ### 2. Run the constraint radar post-processing
#
# Use `constraint_names` to select the constraints to display:
execute_post(
    "sobieski_mdf_scenario.h5",
    settings_model=ConstraintRadar_Settings(
        constraint_names=["g_1", "g_2", "g_3"],
        save=False,
        show=True,
    ),
)

# %%
# ## Summary
#
# [ConstraintRadar][gemseo.post.constraint_radar.ConstraintRadar] displays
# selected constraints on a radar chart at the last iteration by default.
# It is particularly suited when the number of constraints is large.
# Pass any HDF5 file from a previously executed scenario to
# [execute_post()][gemseo.execute_post].
