# Copyright 2021 IRT Saint Exupéry, https://www.irt-saintexupery.com
#
# This work is licensed under a BSD 0-Clause License.
#
# Permission to use, copy, modify, and/or distribute this software
# for any purpose with or without fee is hereby granted.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL
# WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL
# THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT,
# OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING
# FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT,
# NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION
# WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
"""# Pareto front

## Problem

After an optimisation or a DOE, you want to identify the trade-off between
two or more objectives and visualise the Pareto-optimal points.

## Solution

Use [ParetoFront][gemseo.post.pareto_front.ParetoFront],
which produces a matrix of scatter plots for the selected objectives.
Locally non-dominated points for each objective are shown in red;
globally Pareto-optimal points (across all objectives) are shown in green.

## Step-by-step guide
"""

from __future__ import annotations

from gemseo import execute_post
from gemseo.settings.post import ParetoFront_Settings

# %%
# ### 1. Prerequisites
#
# This how-to requires an HDF5 file generated by a previously executed scenario.
# See [How to post-process an HDF5 file][post-process-an-hdf5-file]
# for more information on how to generate and load such a file.
#
# !!! note
#     The `execute_post` function also handles previously executed instances of `MDOScenario`
#     or `OptimzationProblem`.

# %%
# ### 2. Run the Pareto front post-processing
#
# Use `objectives` to select the functions to include in the Pareto analysis:
# Use `objectives_labels` to assign readable labels to the objective components:
execute_post(
    "sobieski_mdf_scenario.h5",
    settings_model=ParetoFront_Settings(
        objectives=["g_3", "-y_4"],
        save=False,
        show=True,
    ),
)

# %%
# ## Summary
#
# [ParetoFront][gemseo.post.pareto_front.ParetoFront] identifies and visualises
# trade-offs between selected objectives.
# Red points are locally non-dominated for a given objective;
# green points are globally Pareto-optimal across all selected objectives.
# Pass any HDF5 file from a previously executed scenario to
# [execute_post()][gemseo.execute_post].
