# Copyright 2021 IRT Saint Exupéry, https://www.irt-saintexupery.com
#
# This work is licensed under a BSD 0-Clause License.
#
# Permission to use, copy, modify, and/or distribute this software
# for any purpose with or without fee is hereby granted.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL
# WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL
# THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT,
# OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING
# FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT,
# NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION
# WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

# Contributors:
#    INITIAL AUTHORS - initial API and implementation and/or initial
#                           documentation
#        :author: Matthias De Lozzo
#    OTHER AUTHORS   - MACROSCOPIC CHANGES
"""# Self-Organizing Map

## Problem

After an optimisation or a DOE, you want a qualitative 2D overview of how
the objective function and constraints behave across the design space,
even when the design space has a high dimension.

## Solution

Use [SOM][gemseo.post.som.SOM], which builds a Self-Organizing Map (SOM):
an unsupervised neural network that reduces the design space to a 2D grid of neurons.
Each neuron is coloured according to the average value of a chosen criterion
for the samples clustered around it,
giving a qualitative view of the objective, the constraints,
and their relative behaviours.

!!!quote "References"
    T. Kohonen et al. Self-Organizing Maps. Springer, 3rd edition, 2001.

## Step-by-step guide
"""

from __future__ import annotations

from gemseo import execute_post
from gemseo.settings.post import SOM_Settings

# %%
# ### 1. Prerequisites
#
# This how-to requires an HDF5 file generated by a previously executed scenario.
# See [How to post-process an HDF5 file][post-process-an-hdf5-file]
# for more information on how to generate and load such a file.
# !!!note
#     The `execute_post` function also handles previously executed instances of `MDOScenario`
#     or `OptimzationProblem`.
#
# !!! note
#
#     A SOM requires a sufficient number of evaluations to produce meaningful results.
#     A white neuron on the map means no sample was close enough to it:
#     not enough evaluations were provided to train the SOM.
#     A DOE with a large number of samples (e.g. 10 000 points) produces
#     more relevant SOM plots than a gradient-based optimisation history.

# %%
# ### 2. Run the SOM post-processing
#
execute_post(
    "sobieski_mdf_scenario.h5",
    settings_model=SOM_Settings(save=False, show=True),
)

# %%
# ## Summary
#
# [SOM][gemseo.post.som.SOM] projects the optimisation or DOE history onto a 2D
# neuron grid, colouring each neuron by the average criterion value of its samples.
# It provides a qualitative view of the objective and constraints across the design space.
# Pass any HDF5 file from a previously executed scenario or DOE to
# [execute_post()][gemseo.execute_post].
