# Copyright 2021 IRT Saint Exupéry, https://www.irt-saintexupery.com
#
# This work is licensed under a BSD 0-Clause License.
#
# Permission to use, copy, modify, and/or distribute this software
# for any purpose with or without fee is hereby granted.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL
# WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL
# THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT,
# OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING
# FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT,
# NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION
# WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
"""# History plot of problem functions

## Problem

After an optimisation or a DOE, you want to plot the evolution of selected
problem functions across iterations or sampling snapshots.

## Solution

Use [BasicHistory][gemseo.post.basic_history.BasicHistory],
which plots any problem function against the iteration index.

## Step-by-step guide
"""

from __future__ import annotations

from gemseo import execute_post
from gemseo.settings.post import BasicHistory_Settings

# %%
# ### 1. Prerequisites
#
# This how-to requires an HDF5 file generated by a previously executed scenario.
# See [How to post-process an HDF5 file][post-process-an-hdf5-file]
# for more information on how to generate and load such a file.
#
# !!! note
#     The `execute_post` function also handles previously executed instances of `MDOScenario`
#     or `OptimzationProblem`.

# %%
# ### 2. Plot the objective history
#
execute_post(
    "sobieski_mdf_scenario.h5",
    settings_model=BasicHistory_Settings(
        variable_names=["y_4"],
        save=False,
        show=True,
    ),
)

# %%
# ### 3. Plot the constraint history
#
execute_post(
    "sobieski_mdf_scenario.h5",
    settings_model=BasicHistory_Settings(
        variable_names=["g_1", "g_2", "g_3"],
        save=False,
        show=True,
    ),
)

# %%
# ## Summary
#
# [BasicHistory][gemseo.post.basic_history.BasicHistory] plots the iteration-by-iteration
# history of any problem function.
# Use `variable_names` to select the functions to display.
# Pass any HDF5 file from a previously executed scenario to
# [execute_post()][gemseo.execute_post].
