# Copyright 2021 IRT Saint Exupéry, https://www.irt-saintexupery.com
#
# This work is licensed under a BSD 0-Clause License.
#
# Permission to use, copy, modify, and/or distribute this software
# for any purpose with or without fee is hereby granted.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL
# WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL
# THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT,
# OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING
# FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT,
# NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION
# WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
"""# Objective history with constraint feasibility

## Problem

After an optimisation, you want to track the objective function history
while keeping an eye on the overall constraint feasibility at each iteration.

## Solution

Use [ObjConstrHist][gemseo.post.obj_constr_hist.ObjConstrHist],
which plots the objective history against the iterations
with a colour-coded background indicating the most violated constraint:
red if violated, white if active, and green if satisfied.

## Step-by-step guide
"""

from __future__ import annotations

from gemseo import execute_post
from gemseo.settings.post import ObjConstrHist_Settings

# %%
# ### 1. Prerequisites
#
# This how-to requires an HDF5 file generated by a previously executed scenario.
# See [How to post-process an HDF5 file][post-process-an-hdf5-file]
# for more information on how to generate and load such a file.
# !!!note
#     The `execute_post` function also handles previously executed instances of `MDOScenario`
#     or `OptimzationProblem`.

# %%
# ### 2. Run the post-processing
#
execute_post(
    "sobieski_mdf_scenario.h5",
    settings_model=ObjConstrHist_Settings(save=False, show=True),
)

# %%
# ## Summary
#
# [ObjConstrHist][gemseo.post.obj_constr_hist.ObjConstrHist] combines the objective
# history with a colour-coded feasibility indicator in a single plot,
# making it easy to correlate objective improvements with constraint satisfaction.
# Pass any HDF5 file from a previously executed scenario to
# [execute_post()][gemseo.execute_post].
