# Copyright 2021 IRT Saint Exupéry, https://www.irt-saintexupery.com
#
# This work is licensed under a BSD 0-Clause License.
#
# Permission to use, copy, modify, and/or distribute this software
# for any purpose with or without fee is hereby granted.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL
# WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL
# THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT,
# OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING
# FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT,
# NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION
# WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
"""# Design variables history on parallel coordinates

## Problem

After an optimisation, you want to visualise how the design variables evolved
across iterations and identify correlations between their values
and the objective function.

## Solution

Use [ParallelCoordinates][gemseo.post.dataset.parallel_coordinates.ParallelCoordinates],
which plots the design variable history as a cobweb chart.
Each vertical axis corresponds to a design variable normalised by its bounds.
Each iteration is represented as a polyline coloured by the objective function value,
highlighting correlations between design variables and objective.

## Step-by-step guide
"""

from __future__ import annotations

from gemseo import execute_post
from gemseo.settings.post import ParallelCoordinates_Settings

# %%
# ### 1. Prerequisites
#
# This how-to requires an HDF5 file generated by a previously executed scenario.
# See [How to post-process an HDF5 file][post-process-an-hdf5-file]
# for more information on how to generate and load such a file.
# !!!note
#     The `execute_post` function also handles previously executed instances of `MDOScenario`
#     or `OptimzationProblem`.

# %%
# ### 2. Run the parallel coordinates post-processing
#
execute_post(
    "sobieski_mdf_scenario.h5",
    settings_model=ParallelCoordinates_Settings(save=False, show=True),
)

# %%
# ## Summary
#
# [ParallelCoordinates][gemseo.post.dataset.parallel_coordinates.ParallelCoordinates]
# displays the design variable history as a cobweb chart coloured by objective value,
# making correlations between design variables and the objective visible at a glance.
# Pass any HDF5 file from a previously executed scenario to
# [execute_post()][gemseo.execute_post].
